services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - book-library_pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer:4
    restart: always
    ports:
      - '8080:8080'

  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - book-library_redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}

  redisinsight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - '5540:5540'

volumes:
  book-library_pg_data:
    external: true
  book-library_redis_data:
    external: true
